//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeHouse9_14.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSale
    {
        public int IdProductSale { get; set; }
        public int IdSale { get; set; }
        public int IdProduct { get; set; }
        public string Quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
